cpp_program:
  executable_path: 'scripts/cpu_version/OMP_FFT.exe'

settings:
  num_threads: 256
  input_file: 'data/numbers_1024.txt'
  device: cpu
  for_limit: 5 


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweeper:
    params:
      settings.input_file: data/numbers_134217728.txt
      settings.num_threads: 256
      settings.device: cuda
      settings.for_limit: 10
