cpp_program:
  executable_path: scripts/gpu_version/build/CUDA_fft.exe

settings:
  num_threads: 64
  input_file: data/numbers_1024.txt
  device: cuda
  num_run: 10

hydra:
  run:
    dir: logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      settings.input_file: data/numbers_2097152.txt, data/numbers_4194304.txt, data/numbers_8388608.txt, data/numbers_16777216.txt, data/numbers_33554432.txt, data/numbers_67108864.txt, data/numbers_134217728.txt
      cpp_program.executable_path: scripts/gpu_version/build/CUDA_fft_v01.exe, scripts/gpu_version/build/CUDA_fft_v05.exe, scripts/gpu_version/build/CUDA_fft_v07.exe
      settings.num_threads: 64, 96
      settings.device: cuda
      settings.num_run: 10