cpp_program:
  executable_path: scripts/gpu_version/build/CUDA_fft.exe

settings:
  num_threads: 64
  input_file: data/numbers_1024.txt
  device: cuda
  num_run: 10

hydra:
  run:
    dir: logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    params:
      cpp_program.executable_path: scripts/gpu_version/build/CUDA_fft_v5.exe
      settings.input_file: data/numbers_2097152.txt, data/numbers_4194304.txt
      settings.num_threads: 256
      settings.device: cuda
      settings.num_run: 10